/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.guitester;

/**
 *
 * @author hurle
 */
public class parentContact extends javax.swing.JFrame {

    /**
     * Creates new form parentContact
     */
    public parentContact() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentNameLbl = new javax.swing.JLabel();
        parentNameTxt = new javax.swing.JTextField();
        teacherInputTxtField = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        teacherMenuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        parentNameLbl.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        parentNameLbl.setText("Parent name ");
        getContentPane().add(parentNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 17, 130, -1));

        parentNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentNameTxtActionPerformed(evt);
            }
        });
        getContentPane().add(parentNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 159, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        teacherInputTxtField.setViewportView(jTextArea1);

        getContentPane().add(teacherInputTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1470, 560));

        teacherMenuButton.setBackground(new java.awt.Color(0, 102, 102));
        teacherMenuButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        teacherMenuButton.setText("Menu");
        teacherMenuButton.setPreferredSize(new java.awt.Dimension(200, 95));
        teacherMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherMenuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(teacherMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 640, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teacherMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherMenuButtonActionPerformed
        new teacherHome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_teacherMenuButtonActionPerformed

    private void parentNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parentNameTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(parentContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(parentContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(parentContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(parentContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new parentContact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel parentNameLbl;
    private javax.swing.JTextField parentNameTxt;
    private javax.swing.JScrollPane teacherInputTxtField;
    private javax.swing.JButton teacherMenuButton;
    // End of variables declaration//GEN-END:variables
}
