/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.guitester;

/**
 *
 * @author hurle
 */
public class setBigO extends javax.swing.JFrame {

    /**
     * Creates new form setBigO
     */
    public setBigO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teacherMenuButton = new javax.swing.JButton();
        ReturnButton = new javax.swing.JButton();
        pastQuesButton = new javax.swing.JButton();
        worksheetButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setMinimumSize(new java.awt.Dimension(1490, 750));
        setPreferredSize(new java.awt.Dimension(1490, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        teacherMenuButton.setBackground(new java.awt.Color(0, 102, 102));
        teacherMenuButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        teacherMenuButton.setText("Menu");
        teacherMenuButton.setMaximumSize(new java.awt.Dimension(200, 95));
        teacherMenuButton.setMinimumSize(new java.awt.Dimension(200, 95));
        teacherMenuButton.setPreferredSize(new java.awt.Dimension(200, 95));
        teacherMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherMenuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(teacherMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 630, -1, -1));

        ReturnButton.setBackground(new java.awt.Color(0, 102, 102));
        ReturnButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        ReturnButton.setText("Return");
        ReturnButton.setMaximumSize(new java.awt.Dimension(200, 95));
        ReturnButton.setMinimumSize(new java.awt.Dimension(200, 95));
        ReturnButton.setPreferredSize(new java.awt.Dimension(200, 95));
        ReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ReturnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 630, -1, -1));

        pastQuesButton.setBackground(new java.awt.Color(0, 102, 102));
        pastQuesButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        pastQuesButton.setText("Past paper questions");
        pastQuesButton.setMaximumSize(new java.awt.Dimension(200, 95));
        pastQuesButton.setMinimumSize(new java.awt.Dimension(200, 95));
        pastQuesButton.setPreferredSize(new java.awt.Dimension(200, 95));
        pastQuesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastQuesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pastQuesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 250, 110));

        worksheetButton.setBackground(new java.awt.Color(0, 102, 102));
        worksheetButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        worksheetButton.setText("Worksheet ");
        worksheetButton.setMaximumSize(new java.awt.Dimension(200, 95));
        worksheetButton.setMinimumSize(new java.awt.Dimension(200, 95));
        worksheetButton.setPreferredSize(new java.awt.Dimension(200, 95));
        worksheetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                worksheetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(worksheetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 250, 110));

        jLabel2.setFont(new java.awt.Font("Mongolian Baiti", 1, 48)); // NOI18N
        jLabel2.setText("Quadrat revision");
        jLabel2.setMinimumSize(new java.awt.Dimension(1490, 750));
        jLabel2.setName(""); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(1490, 750));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 390, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teacherMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherMenuButtonActionPerformed
        new teacherHome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_teacherMenuButtonActionPerformed

    private void ReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButtonActionPerformed
        new setCompOne().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReturnButtonActionPerformed

    private void pastQuesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastQuesButtonActionPerformed
        new setBigOpastQuestions().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pastQuesButtonActionPerformed

    private void worksheetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_worksheetButtonActionPerformed
        new setBigOworksheet().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_worksheetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(setBigO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(setBigO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(setBigO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(setBigO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new setBigO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReturnButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton pastQuesButton;
    private javax.swing.JButton teacherMenuButton;
    private javax.swing.JButton worksheetButton;
    // End of variables declaration//GEN-END:variables
}
