/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.guitester;

/**
 *
 * @author hurle
 */
public class setCompOne extends javax.swing.JFrame {

    /**
     * Creates new form setCompOne
     */
    public setCompOne() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sortingButton = new javax.swing.JButton();
        searchingButton = new javax.swing.JButton();
        bigOButton = new javax.swing.JButton();
        menuButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();
        interpreterButton = new javax.swing.JButton();
        compilerButton = new javax.swing.JButton();
        assemblersButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1490, 750));
        setPreferredSize(new java.awt.Dimension(1490, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sortingButton.setBackground(new java.awt.Color(0, 102, 102));
        sortingButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        sortingButton.setText("Sorting algorithm ");
        sortingButton.setMaximumSize(new java.awt.Dimension(200, 95));
        sortingButton.setMinimumSize(new java.awt.Dimension(200, 95));
        sortingButton.setPreferredSize(new java.awt.Dimension(200, 95));
        sortingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortingButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sortingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 370, 240, 100));

        searchingButton.setBackground(new java.awt.Color(0, 102, 102));
        searchingButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        searchingButton.setText("Searching algorithm");
        searchingButton.setMaximumSize(new java.awt.Dimension(200, 95));
        searchingButton.setMinimumSize(new java.awt.Dimension(200, 95));
        searchingButton.setPreferredSize(new java.awt.Dimension(200, 95));
        searchingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchingButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 240, 100));

        bigOButton.setBackground(new java.awt.Color(0, 102, 102));
        bigOButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        bigOButton.setText("Big O notation ");
        bigOButton.setMaximumSize(new java.awt.Dimension(200, 95));
        bigOButton.setMinimumSize(new java.awt.Dimension(200, 95));
        bigOButton.setPreferredSize(new java.awt.Dimension(200, 95));
        bigOButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigOButtonActionPerformed(evt);
            }
        });
        getContentPane().add(bigOButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 140, 240, 100));

        menuButton.setBackground(new java.awt.Color(0, 102, 102));
        menuButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        menuButton.setText("Menu");
        menuButton.setMaximumSize(new java.awt.Dimension(200, 95));
        menuButton.setMinimumSize(new java.awt.Dimension(200, 95));
        menuButton.setPreferredSize(new java.awt.Dimension(200, 95));
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(menuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 630, -1, -1));

        returnButton.setBackground(new java.awt.Color(0, 102, 102));
        returnButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        returnButton.setText("Return");
        returnButton.setMaximumSize(new java.awt.Dimension(200, 95));
        returnButton.setMinimumSize(new java.awt.Dimension(200, 95));
        returnButton.setPreferredSize(new java.awt.Dimension(200, 95));
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        getContentPane().add(returnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 630, -1, -1));

        interpreterButton.setBackground(new java.awt.Color(0, 102, 102));
        interpreterButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        interpreterButton.setText("Interpreters");
        interpreterButton.setMaximumSize(new java.awt.Dimension(200, 95));
        interpreterButton.setMinimumSize(new java.awt.Dimension(200, 95));
        interpreterButton.setPreferredSize(new java.awt.Dimension(200, 95));
        getContentPane().add(interpreterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 250, 240, 100));

        compilerButton.setBackground(new java.awt.Color(0, 102, 102));
        compilerButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        compilerButton.setText("Compilers");
        compilerButton.setMaximumSize(new java.awt.Dimension(200, 95));
        compilerButton.setMinimumSize(new java.awt.Dimension(200, 95));
        compilerButton.setPreferredSize(new java.awt.Dimension(200, 95));
        compilerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compilerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(compilerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 240, 100));

        assemblersButton.setBackground(new java.awt.Color(0, 102, 102));
        assemblersButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        assemblersButton.setText("Assemblers");
        assemblersButton.setMaximumSize(new java.awt.Dimension(200, 95));
        assemblersButton.setMinimumSize(new java.awt.Dimension(200, 95));
        assemblersButton.setPreferredSize(new java.awt.Dimension(200, 95));
        getContentPane().add(assemblersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 240, 100));

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 48)); // NOI18N
        jLabel1.setText("Quadrat revision");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 380, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sortingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortingButtonActionPerformed
       new setSortingAlgorithm().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_sortingButtonActionPerformed

    private void searchingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchingButtonActionPerformed
        new setSearchingAlgorithm().setVisible(true);
          this.dispose();
    }//GEN-LAST:event_searchingButtonActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        new teacherHome().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_menuButtonActionPerformed

    private void bigOButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigOButtonActionPerformed
   new setBigO().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_bigOButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
       new setAssignments().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_returnButtonActionPerformed

    private void compilerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compilerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compilerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(setCompOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(setCompOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(setCompOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(setCompOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new setCompOne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assemblersButton;
    private javax.swing.JButton bigOButton;
    private javax.swing.JButton compilerButton;
    private javax.swing.JButton interpreterButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton menuButton;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton searchingButton;
    private javax.swing.JButton sortingButton;
    // End of variables declaration//GEN-END:variables
}
