/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.guitester;

/**
 *
 * @author hurle
 */
public class studentSortingAlgorithm extends javax.swing.JFrame {

    /**
     * Creates new form studentSortingAlgorithm
     */
    public studentSortingAlgorithm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        worksheetButton = new javax.swing.JButton();
        pastQuesButton = new javax.swing.JButton();
        reviseContentButton = new javax.swing.JButton();
        studentMenuButton1 = new javax.swing.JButton();
        ReturnButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        worksheetButton.setBackground(new java.awt.Color(0, 102, 102));
        worksheetButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        worksheetButton.setText("Worksheet ");
        worksheetButton.setPreferredSize(new java.awt.Dimension(250, 95));
        worksheetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                worksheetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(worksheetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        pastQuesButton.setBackground(new java.awt.Color(0, 102, 102));
        pastQuesButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        pastQuesButton.setText("Past paper questions");
        pastQuesButton.setPreferredSize(new java.awt.Dimension(250, 95));
        pastQuesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastQuesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pastQuesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        reviseContentButton.setBackground(new java.awt.Color(0, 102, 102));
        reviseContentButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        reviseContentButton.setText("Revise Content ");
        reviseContentButton.setPreferredSize(new java.awt.Dimension(250, 95));
        reviseContentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviseContentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(reviseContentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        studentMenuButton1.setBackground(new java.awt.Color(0, 102, 102));
        studentMenuButton1.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        studentMenuButton1.setText("Menu");
        studentMenuButton1.setPreferredSize(new java.awt.Dimension(200, 95));
        studentMenuButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentMenuButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(studentMenuButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 640, -1, -1));

        ReturnButton.setBackground(new java.awt.Color(0, 102, 102));
        ReturnButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        ReturnButton.setText("Return");
        ReturnButton.setPreferredSize(new java.awt.Dimension(200, 95));
        ReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ReturnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 640, -1, -1));

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 48)); // NOI18N
        jLabel1.setText("Quadrat revision");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 380, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentMenuButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentMenuButton1ActionPerformed
     new studentHome().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_studentMenuButton1ActionPerformed

    private void ReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButtonActionPerformed
       new studentCompOne().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_ReturnButtonActionPerformed

    private void worksheetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_worksheetButtonActionPerformed
     new studentSortingWorksheet().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_worksheetButtonActionPerformed

    private void pastQuesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastQuesButtonActionPerformed
      new studentSortingPastQuestions().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_pastQuesButtonActionPerformed

    private void reviseContentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviseContentButtonActionPerformed
       new studentSortingRevise().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_reviseContentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentSortingAlgorithm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentSortingAlgorithm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentSortingAlgorithm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentSortingAlgorithm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentSortingAlgorithm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReturnButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton pastQuesButton;
    private javax.swing.JButton reviseContentButton;
    private javax.swing.JButton studentMenuButton1;
    private javax.swing.JButton worksheetButton;
    // End of variables declaration//GEN-END:variables
}
