/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.guitester;

/**
 *
 * @author 2-GHurley
 */
public class studentHome extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public studentHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        componentTwoButton = new javax.swing.JButton();
        progressButton = new javax.swing.JButton();
        teacherContactButton = new javax.swing.JButton();
        inboxButton = new javax.swing.JButton();
        componentOneButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        componentTwoButton.setBackground(new java.awt.Color(0, 102, 102));
        componentTwoButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        componentTwoButton.setText("component 2 ");
        componentTwoButton.setMaximumSize(new java.awt.Dimension(220, 95));
        componentTwoButton.setMinimumSize(new java.awt.Dimension(220, 95));
        componentTwoButton.setPreferredSize(new java.awt.Dimension(220, 95));
        componentTwoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                componentTwoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(componentTwoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        progressButton.setBackground(new java.awt.Color(0, 102, 102));
        progressButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        progressButton.setText("progress check ");
        progressButton.setMaximumSize(new java.awt.Dimension(220, 95));
        progressButton.setMinimumSize(new java.awt.Dimension(220, 95));
        progressButton.setPreferredSize(new java.awt.Dimension(220, 95));
        progressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                progressButtonActionPerformed(evt);
            }
        });
        getContentPane().add(progressButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        teacherContactButton.setBackground(new java.awt.Color(0, 102, 102));
        teacherContactButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        teacherContactButton.setText("teacher contact ");
        teacherContactButton.setToolTipText("");
        teacherContactButton.setMaximumSize(new java.awt.Dimension(220, 95));
        teacherContactButton.setMinimumSize(new java.awt.Dimension(220, 95));
        teacherContactButton.setPreferredSize(new java.awt.Dimension(220, 95));
        teacherContactButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherContactButtonActionPerformed(evt);
            }
        });
        getContentPane().add(teacherContactButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 430, -1, -1));

        inboxButton.setBackground(new java.awt.Color(0, 102, 102));
        inboxButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        inboxButton.setText("inbox");
        inboxButton.setMaximumSize(new java.awt.Dimension(220, 95));
        inboxButton.setMinimumSize(new java.awt.Dimension(220, 95));
        inboxButton.setPreferredSize(new java.awt.Dimension(220, 95));
        inboxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inboxButtonActionPerformed(evt);
            }
        });
        getContentPane().add(inboxButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 310, -1, -1));

        componentOneButton.setBackground(new java.awt.Color(0, 102, 102));
        componentOneButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        componentOneButton.setText("component 1 ");
        componentOneButton.setMaximumSize(new java.awt.Dimension(220, 95));
        componentOneButton.setMinimumSize(new java.awt.Dimension(220, 95));
        componentOneButton.setPreferredSize(new java.awt.Dimension(220, 95));
        componentOneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                componentOneButtonActionPerformed(evt);
            }
        });
        getContentPane().add(componentOneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        logOutButton.setBackground(new java.awt.Color(0, 102, 102));
        logOutButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        logOutButton.setText("log out ");
        logOutButton.setMaximumSize(new java.awt.Dimension(220, 95));
        logOutButton.setMinimumSize(new java.awt.Dimension(220, 95));
        logOutButton.setPreferredSize(new java.awt.Dimension(220, 95));
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 540, -1, -1));

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 48)); // NOI18N
        jLabel1.setText("Quadrat revision");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 380, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teacherContactButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherContactButtonActionPerformed
     new teacherContact().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_teacherContactButtonActionPerformed

    private void componentTwoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_componentTwoButtonActionPerformed
      new studentCompTwo().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_componentTwoButtonActionPerformed

    private void componentOneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_componentOneButtonActionPerformed
  new studentCompOne().setVisible(true);
  this.dispose();
    }//GEN-LAST:event_componentOneButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
 new Login().setVisible(true);
 this.dispose();
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void inboxButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inboxButtonActionPerformed
    new studentInbox().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_inboxButtonActionPerformed

    private void progressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progressButtonActionPerformed
     new studentProgressCheck().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_progressButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton componentOneButton;
    private javax.swing.JButton componentTwoButton;
    private javax.swing.JButton inboxButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton progressButton;
    private javax.swing.JButton teacherContactButton;
    // End of variables declaration//GEN-END:variables
}
