/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.guitester;

/**
 *
 * @author hurle
 */
public class studentCompOne extends javax.swing.JFrame {

    /**
     * Creates new form studentCompOne
     */
    public studentCompOne() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchingButton = new javax.swing.JButton();
        bigOButton = new javax.swing.JButton();
        sortingButton = new javax.swing.JButton();
        studentMenuButton1 = new javax.swing.JButton();
        interpreterButton = new javax.swing.JButton();
        compilerButton = new javax.swing.JButton();
        assemblersButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchingButton.setBackground(new java.awt.Color(0, 102, 102));
        searchingButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        searchingButton.setText("Searching algorithm");
        searchingButton.setMinimumSize(null);
        searchingButton.setPreferredSize(new java.awt.Dimension(220, 95));
        searchingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchingButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 200, 240, -1));

        bigOButton.setBackground(new java.awt.Color(0, 102, 102));
        bigOButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        bigOButton.setText("Big O notation ");
        bigOButton.setMinimumSize(null);
        bigOButton.setPreferredSize(new java.awt.Dimension(220, 95));
        bigOButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigOButtonActionPerformed(evt);
            }
        });
        getContentPane().add(bigOButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        sortingButton.setBackground(new java.awt.Color(0, 102, 102));
        sortingButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        sortingButton.setText("Sorting algorithm ");
        sortingButton.setMaximumSize(new java.awt.Dimension(220, 35));
        sortingButton.setMinimumSize(null);
        sortingButton.setPreferredSize(new java.awt.Dimension(220, 95));
        sortingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortingButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sortingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        studentMenuButton1.setBackground(new java.awt.Color(0, 102, 102));
        studentMenuButton1.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        studentMenuButton1.setText("Menu");
        studentMenuButton1.setMinimumSize(null);
        studentMenuButton1.setPreferredSize(new java.awt.Dimension(200, 95));
        studentMenuButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentMenuButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(studentMenuButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 640, -1, -1));

        interpreterButton.setBackground(new java.awt.Color(0, 102, 102));
        interpreterButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        interpreterButton.setText("Interpreters");
        interpreterButton.setMinimumSize(null);
        interpreterButton.setPreferredSize(new java.awt.Dimension(220, 95));
        getContentPane().add(interpreterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 420, 240, -1));

        compilerButton.setBackground(new java.awt.Color(0, 102, 102));
        compilerButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        compilerButton.setText("Compilers");
        compilerButton.setMinimumSize(null);
        compilerButton.setPreferredSize(new java.awt.Dimension(220, 95));
        compilerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compilerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(compilerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 310, 240, -1));

        assemblersButton.setBackground(new java.awt.Color(0, 102, 102));
        assemblersButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        assemblersButton.setText("Assemblers");
        assemblersButton.setMinimumSize(null);
        assemblersButton.setPreferredSize(new java.awt.Dimension(220, 95));
        getContentPane().add(assemblersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 48)); // NOI18N
        jLabel1.setText("Quadrat revision");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 380, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sortingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortingButtonActionPerformed
         new studentSortingAlgorithm().setVisible(true);
          this.dispose();
    }//GEN-LAST:event_sortingButtonActionPerformed

    private void searchingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchingButtonActionPerformed
      new studentSearchingAlgorithm().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_searchingButtonActionPerformed

    private void bigOButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigOButtonActionPerformed
          new studentBigO().setVisible(true);
           this.dispose();
    }//GEN-LAST:event_bigOButtonActionPerformed

    private void studentMenuButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentMenuButton1ActionPerformed
     new studentHome().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_studentMenuButton1ActionPerformed

    private void compilerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compilerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compilerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentCompOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentCompOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentCompOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentCompOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentCompOne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assemblersButton;
    private javax.swing.JButton bigOButton;
    private javax.swing.JButton compilerButton;
    private javax.swing.JButton interpreterButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton searchingButton;
    private javax.swing.JButton sortingButton;
    private javax.swing.JButton studentMenuButton1;
    // End of variables declaration//GEN-END:variables
}
