/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.guitester;

/**
 *
 * @author hurle
 */
public class studentCompTwo extends javax.swing.JFrame {

    /**
     * Creates new form studentCompTwo
     */
    public studentCompTwo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logicButton = new javax.swing.JButton();
        studentMenuButton1 = new javax.swing.JButton();
        SecondaryStorageButton = new javax.swing.JButton();
        networkingButton = new javax.swing.JButton();
        bigDataButton = new javax.swing.JButton();
        architectureButton = new javax.swing.JButton();
        cryptographyButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logicButton.setBackground(new java.awt.Color(0, 102, 102));
        logicButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        logicButton.setText("Boolean Logic");
        logicButton.setPreferredSize(new java.awt.Dimension(220, 95));
        logicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logicButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logicButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        studentMenuButton1.setBackground(new java.awt.Color(0, 102, 102));
        studentMenuButton1.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        studentMenuButton1.setText("Menu");
        studentMenuButton1.setMaximumSize(null);
        studentMenuButton1.setMinimumSize(null);
        studentMenuButton1.setPreferredSize(new java.awt.Dimension(200, 95));
        studentMenuButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentMenuButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(studentMenuButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 640, -1, -1));

        SecondaryStorageButton.setBackground(new java.awt.Color(0, 102, 102));
        SecondaryStorageButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        SecondaryStorageButton.setText("Secondary storage");
        SecondaryStorageButton.setMaximumSize(null);
        SecondaryStorageButton.setMinimumSize(null);
        SecondaryStorageButton.setPreferredSize(new java.awt.Dimension(220, 95));
        getContentPane().add(SecondaryStorageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        networkingButton.setBackground(new java.awt.Color(0, 102, 102));
        networkingButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        networkingButton.setText("Networking");
        networkingButton.setMaximumSize(null);
        networkingButton.setMinimumSize(null);
        networkingButton.setPreferredSize(new java.awt.Dimension(220, 95));
        networkingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkingButtonActionPerformed(evt);
            }
        });
        getContentPane().add(networkingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        bigDataButton.setBackground(new java.awt.Color(0, 102, 102));
        bigDataButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        bigDataButton.setText("Big Data");
        bigDataButton.setMaximumSize(null);
        bigDataButton.setMinimumSize(null);
        bigDataButton.setPreferredSize(new java.awt.Dimension(220, 95));
        getContentPane().add(bigDataButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 420, -1, -1));

        architectureButton.setBackground(new java.awt.Color(0, 102, 102));
        architectureButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        architectureButton.setText("Architecture");
        architectureButton.setMaximumSize(null);
        architectureButton.setMinimumSize(null);
        architectureButton.setPreferredSize(new java.awt.Dimension(220, 95));
        getContentPane().add(architectureButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 310, -1, -1));

        cryptographyButton.setBackground(new java.awt.Color(0, 102, 102));
        cryptographyButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        cryptographyButton.setText("Cryptography");
        cryptographyButton.setMaximumSize(null);
        cryptographyButton.setMinimumSize(null);
        cryptographyButton.setPreferredSize(new java.awt.Dimension(220, 95));
        cryptographyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cryptographyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cryptographyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 200, -1, -1));

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 48)); // NOI18N
        jLabel1.setText("Quadrat revision");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 380, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentMenuButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentMenuButton1ActionPerformed
    new studentHome().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_studentMenuButton1ActionPerformed

    private void logicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logicButtonActionPerformed
     new studentBoolean().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_logicButtonActionPerformed

    private void networkingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_networkingButtonActionPerformed

    private void cryptographyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cryptographyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cryptographyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentCompTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentCompTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentCompTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentCompTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentCompTwo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SecondaryStorageButton;
    private javax.swing.JButton architectureButton;
    private javax.swing.JButton bigDataButton;
    private javax.swing.JButton cryptographyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logicButton;
    private javax.swing.JButton networkingButton;
    private javax.swing.JButton studentMenuButton1;
    // End of variables declaration//GEN-END:variables
}
