/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.guitester;

/**
 *
 * @author 2-GHurley
 */
public class studentContact extends javax.swing.JFrame {

    /**
     * Creates new form parentContact
     */
    public studentContact() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teacherTextField = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        studentNameTextField = new javax.swing.JTextField();
        studentNameLbl = new javax.swing.JLabel();
        teacherMenuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        teacherTextField.setViewportView(jTextArea1);

        getContentPane().add(teacherTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1480, 600));
        getContentPane().add(studentNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 680, 217, 41));

        studentNameLbl.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        studentNameLbl.setText("student name");
        getContentPane().add(studentNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 190, 29));

        teacherMenuButton.setBackground(new java.awt.Color(0, 102, 102));
        teacherMenuButton.setFont(new java.awt.Font("Mongolian Baiti", 0, 24)); // NOI18N
        teacherMenuButton.setText("Menu");
        teacherMenuButton.setPreferredSize(new java.awt.Dimension(200, 95));
        teacherMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherMenuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(teacherMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 640, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teacherMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherMenuButtonActionPerformed
    new teacherHome().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_teacherMenuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentContact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel studentNameLbl;
    private javax.swing.JTextField studentNameTextField;
    private javax.swing.JButton teacherMenuButton;
    private javax.swing.JScrollPane teacherTextField;
    // End of variables declaration//GEN-END:variables
}
