/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.guitester;

/**
 *
 * @author hurle
 */
public class teacherContact extends javax.swing.JFrame {

    /**
     * Creates new form teacherContact
     */
    public teacherContact() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teacherNameTextBox = new javax.swing.JTextField();
        studentTextBox = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        teacherNameLbl = new javax.swing.JLabel();
        studentMenuButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(teacherNameTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 660, 217, 41));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        studentTextBox.setViewportView(jTextArea1);

        getContentPane().add(studentTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1488, 580));

        teacherNameLbl.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        teacherNameLbl.setText("teacher name");
        getContentPane().add(teacherNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 666, 150, 32));

        studentMenuButton1.setBackground(new java.awt.Color(0, 102, 102));
        studentMenuButton1.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        studentMenuButton1.setText("Menu");
        studentMenuButton1.setPreferredSize(new java.awt.Dimension(200, 95));
        studentMenuButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentMenuButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(studentMenuButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 650, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentMenuButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentMenuButton1ActionPerformed
     new studentHome().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_studentMenuButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacherContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacherContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacherContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacherContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacherContact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton studentMenuButton1;
    private javax.swing.JScrollPane studentTextBox;
    private javax.swing.JLabel teacherNameLbl;
    private javax.swing.JTextField teacherNameTextBox;
    // End of variables declaration//GEN-END:variables
}
