/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.guitester;

/**
 *
 * @author 2-GHurley
 */
public class teacherHome extends javax.swing.JFrame {

    /**
     * Creates new form teacherHome
     */
    public teacherHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentContactButton = new javax.swing.JButton();
        progressButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        setAssignmentsButton = new javax.swing.JButton();
        studentContactButton = new javax.swing.JButton();
        inboxButton = new javax.swing.JButton();
        connectionButton = new javax.swing.JButton();
        connectionLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        parentContactButton.setBackground(new java.awt.Color(0, 102, 102));
        parentContactButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        parentContactButton.setText("parent contact");
        parentContactButton.setPreferredSize(new java.awt.Dimension(220, 95));
        parentContactButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentContactButtonActionPerformed(evt);
            }
        });
        getContentPane().add(parentContactButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        progressButton.setBackground(new java.awt.Color(0, 102, 102));
        progressButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        progressButton.setText("progress check");
        progressButton.setPreferredSize(new java.awt.Dimension(220, 95));
        progressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                progressButtonActionPerformed(evt);
            }
        });
        getContentPane().add(progressButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 240, -1, -1));

        logOutButton.setBackground(new java.awt.Color(0, 102, 102));
        logOutButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        logOutButton.setText("log out");
        logOutButton.setPreferredSize(new java.awt.Dimension(220, 95));
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 460, -1, -1));

        setAssignmentsButton.setBackground(new java.awt.Color(0, 102, 102));
        setAssignmentsButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        setAssignmentsButton.setText("set assignments");
        setAssignmentsButton.setPreferredSize(new java.awt.Dimension(220, 95));
        setAssignmentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setAssignmentsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(setAssignmentsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 350, -1, -1));

        studentContactButton.setBackground(new java.awt.Color(0, 102, 102));
        studentContactButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        studentContactButton.setText("student contact ");
        studentContactButton.setPreferredSize(new java.awt.Dimension(220, 95));
        studentContactButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentContactButtonActionPerformed(evt);
            }
        });
        getContentPane().add(studentContactButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        inboxButton.setBackground(new java.awt.Color(0, 102, 102));
        inboxButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        inboxButton.setText("inbox");
        inboxButton.setPreferredSize(new java.awt.Dimension(220, 95));
        inboxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inboxButtonActionPerformed(evt);
            }
        });
        getContentPane().add(inboxButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, -1, -1));

        connectionButton.setBackground(new java.awt.Color(0, 102, 102));
        connectionButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        connectionButton.setText("test connection");
        connectionButton.setPreferredSize(new java.awt.Dimension(220, 95));
        connectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectionButtonActionPerformed(evt);
            }
        });
        getContentPane().add(connectionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 650, -1, -1));

        connectionLabel.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        getContentPane().add(connectionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 680, 127, 30));

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 48)); // NOI18N
        jLabel1.setText("Quadrat revision");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 380, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
   new Login().setVisible(true);
   this.dispose();
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void studentContactButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentContactButtonActionPerformed
    new studentContact().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_studentContactButtonActionPerformed

    private void progressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progressButtonActionPerformed
        new teacherProgressCheck().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_progressButtonActionPerformed

    private void setAssignmentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setAssignmentsButtonActionPerformed
     new setAssignments().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_setAssignmentsButtonActionPerformed

    private void parentContactButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentContactButtonActionPerformed
   new parentContact().setVisible(true);
   this.dispose();
    }//GEN-LAST:event_parentContactButtonActionPerformed

    private void inboxButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inboxButtonActionPerformed
     new teacherInbox().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_inboxButtonActionPerformed

    private void connectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectionButtonActionPerformed
      boolean connect=DBaccess.SQLtestConnection();
      if(connect==true){
          connectionLabel.setText("connection made");
      }else{
          connectionLabel.setText("connection failed");
      }
    }//GEN-LAST:event_connectionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacherHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacherHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacherHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacherHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacherHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connectionButton;
    private javax.swing.JLabel connectionLabel;
    private javax.swing.JButton inboxButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton parentContactButton;
    private javax.swing.JButton progressButton;
    private javax.swing.JButton setAssignmentsButton;
    private javax.swing.JButton studentContactButton;
    // End of variables declaration//GEN-END:variables
}
